### PR TITLE
Fix bug 8046

### PR DESCRIPTION
**Pull request by v-fenguo**
Aborted rule "ServiceImpl_EditStreamPropertyValue" & "ServiceImpl_DeleteStreamPropertyValue"

### CODE REVIEW

**Comment by RongfangWang** [comment]
Reviewed.

**Comment by congysu** [comment]
Add a description for the bug, for now it is shown as "No description provided."  Thanks.

**Comment by RongfangWang** [comment]
Aborted rule "ServiceImpl_EditStreamPropertyValue" & "ServiceImpl_DeleteStreamPropertyValue"

**Comment by v-fenguo** [comment]
Fix the typo from "eTypeElement" to "en". In which eTypeElement is the container var to contain the selected en.

**Pull request merged**
